/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SceneTestRouteImport } from './routes/scene-test'
import { Route as IndexRouteImport } from './routes/index'

const SceneTestRoute = SceneTestRouteImport.update({
  id: '/scene-test',
  path: '/scene-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scene-test': typeof SceneTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scene-test': typeof SceneTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scene-test': typeof SceneTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scene-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scene-test'
  id: '__root__' | '/' | '/scene-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SceneTestRoute: typeof SceneTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scene-test': {
      id: '/scene-test'
      path: '/scene-test'
      fullPath: '/scene-test'
      preLoaderRoute: typeof SceneTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SceneTestRoute: SceneTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
